apiVersion: v1
kind: Service
metadata:
  name: marwaney-service
  namespace: rashid
  labels:
    owner: patrice
spec:
  selector:
    owner: patrice
    type: service
  ports:
  - name: marwaney/ssh-server 
    port: 80
    targetPort: 80
  - name: marwaney/ssh-server
    port: 4000
    targetPort: 4000
    protocol: TCP
  - name: marwaney/ssh-server
    port: 7000
    targetPort: 7000
  externalIPs:
    - 10.0.0.3
  type: NodePort