apiVersion: v1
kind: Service
metadata:
  name: patrice-service
  namespace: rashid
  labels:
    owner: patrice
spec:
  selector:
    owner: patrice
    type: service
  ports:
  - name: patricehub/my_image
    port: 80
    targetPort: 80
    NodePort: 8000
    protocol: TCP
  type: NodePort